let techRandomWords: string[] = [
    'JAVASCRIPT',
    'TYPESCRIPT',
    'REACT',
    'VUE',
    'ANGULAR',
    'NODE.JS',
    'PYTHON',
    'DJANGO',
    'FLASK',
    'EXPRESS',
    'MONGODB',
    'MYSQL',
    'POSTGRESQL',
    'REDIS',
    'RABBITMQ',
    'AWS',
    'GCP',
    'AZURE',
    'DOCKER',
    'KUBERNETES',
    'TERRAFORM',
    'VITE',
    'WEBPACK',
    'BABEL',
    'JEST',
    'CYPRESS',
    'APPLE',
    'GOOGLE',
    'FACEBOOK',
    'INSTAGRAM',
    'TWITTER',
    'LINKEDIN',
    'SNAPCHAT',
    'PINTEREST',
    'TIKTOK',
    'WHATSAPP',
    'SIGNAL',
    'SKYPE',
    'DISCORD',
    'SLACK',
    'ZOOM',
    'GOOGLE WORKSPACE',
    'NINTENDO',
    'SONY',
    'XBOX',
    'PLAYSTATION',
    'NINTENDO SWITCH',
    'MICROSOFT',
    'RESIDENT EVIL ZERO',
    'GOD OF WAR',
    'RED DEAD REDEMPTION',
    'THE LEGEND OF ZELDA',
    'FINAL FANTASY',
    'THE LEGEND OF ZELDA OCARINA OF TIME',
    'GTA',
    'THE SIMS',
    'CALL OF DUTY',
    'CALL OF DUTY BLACK OPS ',
    'CALL OF DUTY MODERN WARFARE',
    'FORTNITE',
    'MINECRAFT',
    'WORLD OF WARCRAFT',
    'DIABLO',
    'OVERWATCH',
    'BORDERLANDS',
    'CYBERPUNK',
    'RED DEAD REDEMPTION',
    'MARIO',
    'SUPER MARIO ODYSSEY',
    'HALO',
    'RESIDENT EVIL',
    'COMPUTADORA',
    'TECLADO',
    'MOUSE',
    'MONITOR',
    'MOUSEPAD',
    'TABLET',
]

export const getRandomWord = () => {
    const randomIndex = Math.floor(Math.random() * techRandomWords.length)

    return techRandomWords[randomIndex]


}